version = 1

test_patterns = [
    "test/**/*.go",
    "*_test.go",
    "test_*.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/chsatyap/mosn"]
  dependencies_vendored = true
